import { useState, useMemo } from 'react'
import { motion } from 'framer-motion'
import { Settings, MapPin, Eye, FolderHeart, Users, Flame, ChevronRight, Edit3 } from 'lucide-react'
import { userProfile, places } from '../data/mockData'
import { useToast } from '../components/Toast'
import SettingsSheet from '../components/SettingsSheet'

// Explicit color maps — dynamic `bg-${color}/10` classes are never generated by Tailwind
const statColors = {
  coral:    { bg: 'bg-coral/10',    text: 'text-coral' },
  mint:     { bg: 'bg-mint/10',     text: 'text-mint' },
  sky:      { bg: 'bg-sky/10',      text: 'text-sky' },
  lavender: { bg: 'bg-lavender/10', text: 'text-lavender' },
}

function StatCard({ icon: Icon, value, label, color }) {
  const { bg, text } = statColors[color] || statColors.coral
  return (
    <motion.div
      whileHover={{ y: -2 }}
      className="bg-white rounded-2xl p-3 border border-sand/40 text-center shadow-sm"
    >
      <div className={`w-9 h-9 rounded-xl mx-auto mb-2 flex items-center justify-center ${bg}`}>
        <Icon size={16} className={text} />
      </div>
      <p className="text-lg font-bold text-navy">{value}</p>
      <p className="text-[11px] text-warm-gray mt-0.5">{label}</p>
    </motion.div>
  )
}

function BadgeItem({ badge, index }) {
  const showToast = useToast()
  return (
    <motion.div
      whileHover={{ scale: 1.05 }}
      whileTap={{ scale: 0.95 }}
      onClick={() => showToast({ message: `${badge.name}: ${badge.description}`, type: 'info' })}
      className="flex flex-col items-center gap-1.5 p-3 bg-white rounded-2xl border border-sand/40 shadow-sm cursor-pointer"
    >
      <span className="text-2xl">{badge.emoji}</span>
      <p className="text-xs font-semibold text-navy text-center leading-tight">{badge.name}</p>
      <p className="text-[10px] text-warm-gray text-center leading-tight">{badge.description}</p>
    </motion.div>
  )
}

const categoryStyle = [
  'bg-coral/10 text-coral',
  'bg-amber/10 text-amber',
  'bg-mint/10 text-mint',
]
const categoryEmoji = { restaurant: '🍽️', cafe: '☕', park: '🌿', bar: '🍸', museum: '🎨' }

export default function ProfilePage({ isSaved }) {
  const showToast = useToast()
  const [settingsOpen, setSettingsOpen] = useState(false)
  const savedCount = useMemo(() => places.filter(p => isSaved(p.id)).length, [isSaved])

  return (
    <div className="min-h-screen pb-24">
      {/* Hero header */}
      <div className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-coral via-coral-light to-peach" />
        <motion.div
          animate={{ y: [0, -10, 0] }}
          transition={{ duration: 6, repeat: Infinity }}
          className="absolute top-8 right-8 w-24 h-24 rounded-full bg-white/10"
        />
        <motion.div
          animate={{ y: [0, 8, 0] }}
          transition={{ duration: 5, repeat: Infinity, delay: 1 }}
          className="absolute bottom-12 left-4 w-16 h-16 rounded-full bg-white/10"
        />

        <div className="relative z-10 px-5 pt-12 pb-8">
          <div className="flex items-center justify-end mb-6">
            <motion.button
              whileTap={{ scale: 0.9 }}
              onClick={() => setSettingsOpen(true)}
              className="w-9 h-9 rounded-full glass flex items-center justify-center"
            >
              <Settings size={18} className="text-white" />
            </motion.button>
          </div>

          <div className="flex items-center gap-4">
            <div className="relative">
              <img
                src={userProfile.avatar}
                alt={userProfile.name}
                className="w-20 h-20 rounded-full object-cover border-2 border-white/50 shadow-lg"
              />
              <motion.button
                whileTap={{ scale: 0.85 }}
                onClick={() => showToast({ message: 'Edit profile — coming soon!', type: 'info' })}
                className="absolute -bottom-1 -right-1 w-7 h-7 rounded-full bg-white shadow-md flex items-center justify-center"
              >
                <Edit3 size={12} className="text-coral" />
              </motion.button>
            </div>
            <div className="flex-1 min-w-0">
              <h1 className="text-2xl font-bold text-white">{userProfile.name}</h1>
              <p className="text-white/70 text-sm">{userProfile.username}</p>
              <p className="text-white/80 text-sm mt-1">{userProfile.bio}</p>
            </div>
          </div>

          <div className="mt-4 inline-flex items-center gap-2 bg-white/15 rounded-xl px-4 py-2.5 backdrop-blur-sm">
            <Flame size={18} className="text-amber" />
            <span className="text-white font-semibold text-sm">{userProfile.streak}-day streak!</span>
            <span className="text-white/60 text-xs">Keep exploring</span>
          </div>
        </div>
      </div>

      {/* Stats grid */}
      <div className="px-5 mt-4">
        <div className="grid grid-cols-4 gap-2">
          <StatCard icon={MapPin}      value={savedCount}                 label="Saved"   color="coral" />
          <StatCard icon={Eye}         value={userProfile.visitedPlaces}  label="Visited" color="mint" />
          <StatCard icon={FolderHeart} value={userProfile.collections}    label="Lists"   color="sky" />
          <StatCard icon={Users}       value={userProfile.friendCount}    label="Friends" color="lavender" />
        </div>
      </div>

      {/* Badges */}
      <div className="mt-6 px-5">
        <div className="flex items-center justify-between mb-3">
          <h2 className="font-bold text-navy text-base">Badges</h2>
          <button
            onClick={() => showToast({ message: 'All badges — coming soon!', type: 'info' })}
            className="text-coral text-sm font-medium flex items-center gap-0.5"
          >
            All <ChevronRight size={14} />
          </button>
        </div>
        <div className="grid grid-cols-4 gap-2">
          {userProfile.badges.map((badge, i) => (
            <BadgeItem key={badge.id} badge={badge} index={i} />
          ))}
        </div>
      </div>

      {/* Top Categories */}
      <div className="mt-6 px-5">
        <h2 className="font-bold text-navy text-base mb-3">Your Top Categories</h2>
        <div className="flex gap-2 flex-wrap">
          {userProfile.topCategories.map((cat, i) => (
            <div
              key={cat}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-xl ${categoryStyle[i]} font-medium text-sm`}
            >
              <span>{categoryEmoji[cat]}</span>
              <span className="capitalize">{cat}s</span>
            </div>
          ))}
        </div>
      </div>

      {/* Settings shortcut */}
      <div className="mt-6 px-5">
        <motion.button
          whileTap={{ scale: 0.97 }}
          onClick={() => setSettingsOpen(true)}
          className="w-full flex items-center gap-4 p-4 bg-white rounded-2xl border border-sand/40 shadow-sm"
        >
          <div className="w-10 h-10 rounded-xl bg-sand/40 flex items-center justify-center">
            <Settings size={18} className="text-slate" />
          </div>
          <span className="flex-1 text-left font-semibold text-navy text-sm">Settings & Preferences</span>
          <ChevronRight size={16} className="text-warm-gray" />
        </motion.button>
      </div>

      <p className="text-center text-warm-gray text-xs mt-6 mb-4">
        Member since {userProfile.joinDate}
      </p>

      <SettingsSheet isOpen={settingsOpen} onClose={() => setSettingsOpen(false)} />
    </div>
  )
}
